# Site settings
title: Awesome Title to Come Later
description: > # this means to ignore newlines until "baseurl:"
  A blog that you should check occasionally if you like things
  like code, beer, design, music, technology, random rants, and
  general fun stuff.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://elanttam.com" # the base hostname & protocol for your site
twitter_username: elanttam
github_username:  elanttam

# Build settings
markdown: kramdown
